spring.application.name=ShopSphere

# Connection URL (Replace 'localhost:5432/mydb' with your host:port/database)
spring.datasource.url=jdbc:postgresql://localhost:5432/shopsphere

# Database Credentials
spring.datasource.username=postgres
spring.datasource.password=password

# Driver Class Name (Optional in newer Spring Boot versions, but good practice)
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Settings
# 'update' automatically updates your DB schema based on your Java entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT details
jwt.token=6dxjem4XlbNg7PED4pLnCCL7xdnlQ0+jyJHe73Ux9xfxJFik5hnAbyhNK/E4fNbDsuj1DGF0+u8T9uHgXKztSw==
jwt.expiration=86400000
jwt.refresh=604800000
